✨ feat: 스터디 리스트 검색 기능 추가
Quartett/StudyUs-BE pull request #21
Opened 2023-12-20 11:11 UTC by bardnia

title, content를 검색하도록 구현했습니다.

2023-12-21 06:49 UTC, Alexmint001 approved these changes

2023-12-21 07:10 UTC, Nam-Younghoon requested changes
피그마 확인 후에, 검색조건 정책을 다시 잡아주세요
저희 기획상 빠진 필터가 몇개 있습니다

2023-12-22 00:16 UTC, su2minig approved these changes

2023-12-22 00:42 UTC, Nam-Younghoon approved these changes

2023-12-22 00:42 UTC, merged